; Square Wave 0 :: [Timer,Lenght]=[$4002,$4003]
; 7 values
Data_at9D22:
.incbin "sounds/data/sound-data-at9D22.bin"
;
; Square Wave 0 :: [Duty,Sweep]=[$4000,$4001]
Data_at9DB4:
.incbin "sounds/data/sound-data-at9DB4.bin"
;
Data_at9E84:
.incbin "sounds/data/sound-data-at9E84.bin"
;
Data_at9EB4:
;.incbin "sounds/data/sound-data-at9EB4.bin"
.word Data_at9EE7, Data_at9F37, Data_at9F77, Data_at9FE1  
.word Data_at9FE6, Data_at9FEF, Data_at9FF8, Data_atA04B
.word Data_atA050, Data_atA055, Data_atA07B, Data_atA087
.word Data_atA093, Data_atA09E, Data_atA0A9, Data_atA0AE
.word Data_atA147

Data_at9ED6:
.incbin "sounds/data/sound-data-at9ED6.bin"

Data_at9EE7:
.incbin "sounds/data/sound-data-at9EE7.bin"

Data_at9F37:
.incbin "sounds/data/sound-data-at9F37.bin"

Data_at9F77:
.incbin "sounds/data/sound-data-at9F77.bin"

Data_at9FE1:
.byte $84, $04
.word Data_atA1CB
.byte $86

Data_at9FE6:
.byte $84, $02
.word Data_atA200
.byte $84, $02
.word Data_atA235
.byte $86

Data_at9FEF:
.byte $84, $02

.word Data_atA266
.byte $84, $02

.word Data_atA309
.byte $86

Data_at9FF8:
.incbin "sounds/data/sound-data-at9FF8.bin"

Data_atA04B:
.byte $89, $5A, $82, $10, $86

Data_atA050:
.byte $80, $17, $26, $04, $86

Data_atA055:
.incbin "sounds/data/sound-data-atA055.bin"

Data_atA07B:
.byte $80, $0F, $28, $04, $2C, $04, $2E, $08, $81, $04, $83, $86

Data_atA087:
.byte $80, $00, $2D, $05, $81, $02, $83, $26, $02, $28, $02, $86

Data_atA093:
.byte $80, $00, $28, $05, $24, $05, $27, $05, $23, $05, $86

Data_atA09E:
.byte $80, $0B, $10, $03, $0F, $03, $0C, $03, $07, $03, $86

Data_atA0A9:
.byte $80, $17, $2F, $08, $86

Data_atA0AE:
.incbin "sounds/data/sound-data-atA0AE.bin"

Data_atA147:
.incbin "sounds/data/sound-data-atA147.bin"

Data_atA1CB:
.incbin "sounds/data/sound-data-atA1CB.bin"

Data_atA200:
.incbin "sounds/data/sound-data-atA200.bin"

Data_atA235:
.incbin "sounds/data/sound-data-atA235.bin"

Data_atA266:
.incbin "sounds/data/sound-data-atA266.bin"

Data_atA309:
.incbin "sounds/data/sound-data-atA309.bin"