
.word DATA_ADDR_81, DATA_ADDR_82, DATA_ADDR_83, DATA_ADDR_84, DATA_ADDR_85 
.word DATA_ADDR_82, DATA_ADDR_86, DATA_ADDR_87, DATA_ADDR_88, DATA_ADDR_83
.word DATA_ADDR_84, DATA_ADDR_89, DATA_ADDR_90, DATA_ADDR_91, DATA_ADDR_92 

.word $ffff

DATA_ADDR_81: ; $b90d
.incbin "rom-prg/objects/data-block-atB90D.bin"

DATA_ADDR_82: ; $b936
.incbin "rom-prg/objects/data-block-atB936.bin"

DATA_ADDR_83: ; $b95a
.incbin "rom-prg/objects/data-block-atB95A.bin"

DATA_ADDR_85: ; $b986
.incbin "rom-prg/objects/data-block-atB986.bin"

DATA_ADDR_86: ; $b9b2
.incbin "rom-prg/objects/data-block-atB9B2.bin"

DATA_ADDR_87: ; $b9f2
.incbin "rom-prg/objects/data-block-atB9F2.bin"

DATA_ADDR_88: ; $ba1b
.incbin "rom-prg/objects/data-block-atBA1B.bin"

DATA_ADDR_89: ; $ba5b
.incbin "rom-prg/objects/data-block-atBA5B.bin"

DATA_ADDR_84: ; $ba87
.incbin "rom-prg/objects/data-block-atBA87.bin"

DATA_ADDR_90: ; $bab5
.incbin "rom-prg/objects/data-block-atBAB5.bin"

DATA_ADDR_91: ; $baeb
.incbin "rom-prg/objects/data-block-atBAEB.bin"

DATA_ADDR_92: ; $bb56
.incbin "rom-prg/objects/data-block-atBB56.bin"