
.word Data_atC945 ;$c945
.word Data_atC951 ;$c951
.word Data_atC95D ;$c95d
.word Data_atC969 ;$c969
.word Data_atC975 ;$c975
.word Data_atC981 ;$c981
.word Data_atC98D ;$c98d
.word Data_atC999 ;$c999 
.word Data_atC9A5 ;$c9a5
.word Data_atC9B1 ;$c9b1
.word Data_atC9BD ;$c9bd
.word Data_atC9C9 ;$c9c9 
.word Data_atC9D5 ;$c9d5
.word Data_atC9E1 ;$c9e1
.word Data_atC9ED ;$c9ed
.word Data_atC9F9 ;$c9f9 
.word Data_atCA05 ;$ca05
.word Data_atCA11 ;$ca11 ////
.word Data_atCA1D ;$ca1d
.word Data_atCA29 ;$ca29
.word Data_atCA35 ;$ca35
.word Data_atCA41 ;$ca41
.word Data_atCA4D ;$ca4d
.word Data_atCA59 ;$ca59 
.word Data_atCA65 ;$ca65
.word Data_atCA71 ;$ca71
.word Data_atCA7D ;$ca7d
.word Data_atCA89 ;$ca89  
.word Data_atCA95 ;$ca95
.word Data_atCAA1 ;$caa1
.word Data_atCAAD ;$caad
.word Data_atCAB9 ;$cab9 
.word Data_atCAC5 ;$cac5
.word Data_atCAD1 ;$cad1
.word Data_atCADD ;$cadd
.word Data_atCAE9 ;$cae9 
.word Data_atCAF5 ;$caf5
.word Data_atCB01 ;$cb01
.word Data_atCB0D ;$cb0d
.word Data_atCB19 ;$cb19 
.word Data_atCB25 ;$cb25
.word Data_atCB31 ;$cb31
.word Data_atCB3D ;$cb3d
.word Data_atCB49 ;$cb49 
.word Data_atCB55 ;$cb55
.word Data_atCB61 ;$cb61
.word Data_atCB6D ;$cb6d
.word Data_atCB79 ;$cb79 
.word Data_atCB85 ;$cb85
.word Data_atCB91 ;$cb91
.word Data_atCB9D ;$cb9d
.word Data_atCBA9 ;$cba9 
.word Data_atCBB5 ;$cbb5
.word Data_atCBC1 ;$cbc1
.word Data_atCBCD ;$cbcd
.word Data_atCBD9 ;$cbd9 
.word Data_atCBE5 ;$cbe5
.word Data_atCBF1 ;$cbf1
.word Data_atCBFD ;$cbfd
.word Data_atCC09 ;$cc09 
.word Data_atCC15 ;$cc15
.word Data_atCC21 ;$cc21
.word Data_atCC2D ;$cc2d
.word Data_atCC39 ;$cc39 
.word Data_atCC45 ;$cc45
.word Data_atCC51 ;$cc51
.word Data_atCC5D ;$cc5d
.word Data_atCC69 ;$cc69 
.word Data_atCC75 ;$cc75
.word Data_atCC81 ;$cc81

Data_atC945:
.word Data_atCC8D ;$cc8d 
.incbin "rom-prg/objects/data-block-atC947.bin"

Data_atC951:
.word Data_atCCF5 ;$ccf5 
.incbin "rom-prg/objects/data-block-atC953.bin"

Data_atC95D:
.word Data_atCD5D ;$cd5d
.incbin "rom-prg/objects/data-block-atC95F.bin"

Data_atC969:
.word Data_atCE2B ;$ce2b
.incbin "rom-prg/objects/data-block-atC96B.bin"

Data_atC975:
.word Data_atCE41 ;$ce41
.incbin "rom-prg/objects/data-block-atC977.bin"

Data_atC981:
.word Data_atCE57 ;$ce57
.incbin "rom-prg/objects/data-block-atC983.bin"

Data_atC98D:
.word Data_atCEAC ;$ceac
.incbin "rom-prg/objects/data-block-atC98F.bin"

Data_atC999:
.word Data_atCF01 ;$cf01
.incbin "rom-prg/objects/data-block-atC99B.bin"

Data_atC9A5:
.word Data_atCF80 ;$cf80
.incbin "rom-prg/objects/data-block-atC9A7.bin"

Data_atC9B1:
.word Data_atD00D ;$d00d
.incbin "rom-prg/objects/data-block-atC9B3.bin"

Data_atC9BD:
.word Data_atD09A ;$d09a
.incbin "rom-prg/objects/data-block-atC9BF.bin"

Data_atC9C9:
.word Data_atD127 ;$d127
.incbin "rom-prg/objects/data-block-atC9CB.bin"

Data_atC9D5:
.word Data_atD1B4 ;$d1b4
.incbin "rom-prg/objects/data-block-atC9D7.bin"

Data_atC9E1:
.word Data_atD241 ;$d241
.incbin "rom-prg/objects/data-block-atC9E3.bin"

Data_atC9ED:
.word Data_atD291 ;$d291
.incbin "rom-prg/objects/data-block-atC9EF.bin"

Data_atC9F9:
.word Data_atD2E1 ;$d2E1
.incbin "rom-prg/objects/data-block-atC9FB.bin"

Data_atCA05:
.word Data_atD331 ;$d331
.incbin "rom-prg/objects/data-block-atCA07.bin" 

Data_atCA11:
.word Data_atD381 ;$d381
.incbin "rom-prg/objects/data-block-atCA13.bin" 

Data_atCA1D:
.word Data_atD3C1 ;$d3c1
.incbin "rom-prg/objects/data-block-atCA1F.bin";$ca1d

Data_atCA29:
.word Data_atD401 ;$d401
.incbin "rom-prg/objects/data-block-atCA31.bin";$ca29

Data_atCA35:
.word Data_atD426 ;$d426
.incbin "rom-prg/objects/data-block-atCA37.bin";$ca35

Data_atCA41:
.word Data_atD448 ;$d448
.incbin "rom-prg/objects/data-block-atCA43.bin";$ca41

Data_atCA4D:
.word $d502
.incbin "rom-prg/objects/data-block-atCA4F.bin";$ca4d

Data_atCA59:
.word $d52e
.incbin "rom-prg/objects/data-block-atCA5B.bin";$ca59 

Data_atCA65:
.word $d5aa
.incbin "rom-prg/objects/data-block-atCA67.bin";$ca65

Data_atCA71:
.word $d630
.incbin "rom-prg/objects/data-block-atCA73.bin";$ca71

Data_atCA7D:
.word $d6b6
.incbin "rom-prg/objects/data-block-atCA7F.bin";$ca7d

Data_atCA89:
.word $d73c
.incbin "rom-prg/objects/data-block-atCA8B.bin";$ca89  

Data_atCA95:
.word $d7c2
.incbin "rom-prg/objects/data-block-atCA97.bin";$ca95

Data_atCAA1:
.word $d848
.incbin "rom-prg/objects/data-block-atCAA3.bin";$caa1

Data_atCAAD:
.word $d860
.incbin "rom-prg/objects/data-block-atCAAF.bin";$caad

Data_atCAB9:
.word $d878
.incbin "rom-prg/objects/data-block-atCABB.bin";$cab9 

Data_atCAC5:
.word $d88d
.incbin "rom-prg/objects/data-block-atCAC7.bin";$cac5

Data_atCAD1:
.word $d8a2
.incbin "rom-prg/objects/data-block-atCAD3.bin";$cad1

Data_atCADD:
.word $d8b1
.incbin "rom-prg/objects/data-block-atCADF.bin";$cadd

Data_atCAE9:
.word $d8c0
.incbin "rom-prg/objects/data-block-atCAEB.bin";$cae9 

Data_atCAF5:
.word $d905
.incbin "rom-prg/objects/data-block-atCAF7.bin";$caf5

Data_atCB01:
.word $d97c
.incbin "rom-prg/objects/data-block-atCB03.bin";$cb01

Data_atCB0D:
.word $d9f9
.incbin "rom-prg/objects/data-block-atCB0F.bin";$cb0d

Data_atCB19:
.word $da76
.incbin "rom-prg/objects/data-block-atCB1B.bin";$cb19 

Data_atCB25:
.word $daf3
.incbin "rom-prg/objects/data-block-atCB27.bin";$cb25

Data_atCB31:
.word $db6a
.incbin "rom-prg/objects/data-block-atCB33.bin";$cb31

Data_atCB3D:
.word $dbe7
.incbin "rom-prg/objects/data-block-atCB3F.bin";$cb3d

Data_atCB49:
.word $dc64
.incbin "rom-prg/objects/data-block-atCB4B.bin";$cb49 

Data_atCB55:
.word $dce1
.incbin "rom-prg/objects/data-block-atCB57.bin";$cb55

Data_atCB61:
.word $dd9b
.incbin "rom-prg/objects/data-block-atCB63.bin";$cb61

Data_atCB6D:
.word $dda0
.incbin "rom-prg/objects/data-block-atCB6F.bin";$cb6d

Data_atCB79:
.word $dda5
.incbin "rom-prg/objects/data-block-atCB7B.bin";$cb79 

Data_atCB85:
.word $ddaa
.incbin "rom-prg/objects/data-block-atCB87.bin";$cb85

Data_atCB91:
.word $de0f
.incbin "rom-prg/objects/data-block-atCB93.bin";$cb91

Data_atCB9D:
.word $de78
.incbin "rom-prg/objects/data-block-atCB9F.bin";$cb9d

Data_atCBA9:
.word $dedd
.incbin "rom-prg/objects/data-block-atCBAB.bin";$cba9 

Data_atCBB5:
.word $df45
.incbin "rom-prg/objects/data-block-atCBB7.bin";$cbb5

Data_atCBC1:
.word $dfaa
.incbin "rom-prg/objects/data-block-atCBC3.bin";$cbc1

Data_atCBCD:
.word $e013
.incbin "rom-prg/objects/data-block-atCBCF.bin";$cbcd

Data_atCBD9:
.word $e078
.incbin "rom-prg/objects/data-block-atCBDB.bin";$cbd9 

Data_atCBE5:
.word $e0e1
.incbin "rom-prg/objects/data-block-atCBE7.bin";$cbe5

Data_atCBF1:
.word $e0f3
.incbin "rom-prg/objects/data-block-atCBF3.bin";$cbf1

Data_atCBFD:
.word $e109
.incbin "rom-prg/objects/data-block-atCBFF.bin";$cbfd

Data_atCC09:
.word $e142
.incbin "rom-prg/objects/data-block-atCC0B.bin";$cc09 

Data_atCC15:
.word $e161
.incbin "rom-prg/objects/data-block-atCC17.bin";$cc15

Data_atCC21:
.word $e180
.incbin "rom-prg/objects/data-block-atCC23.bin";$cc21

Data_atCC2D:
.word $e19f
.incbin "rom-prg/objects/data-block-atCC2F.bin";$cc2d

Data_atCC39:
.word $e1be
.incbin "rom-prg/objects/data-block-atCC3B.bin";$cc39 

Data_atCC45:
.word $e1dd
.incbin "rom-prg/objects/data-block-atCC47.bin";$cc45

Data_atCC51:
.word $e1fc
.incbin "rom-prg/objects/data-block-atCC53.bin";$cc51

Data_atCC5D:
.word $e21b
.incbin "rom-prg/objects/data-block-atCC5F.bin";$cc5d

Data_atCC69:
.word $e262
.incbin "rom-prg/objects/data-block-atCC6B.bin";$cc69 

Data_atCC75:
.word $e2b5
.incbin "rom-prg/objects/data-block-atCC77.bin";$cc75

Data_atCC81:
.word $e801
.incbin "rom-prg/objects/data-block-atCC83.bin";$cc81

; ===; Each one of the above has one below (enemy AI?)

Data_atCC8D:
.incbin "rom-prg/objects/data-block-atCC8D.bin"

Data_atCCF5:
.incbin "rom-prg/objects/data-block-atCCF5.bin"

Data_atCD5D:
.incbin "rom-prg/objects/data-block-atCC5D.bin"

Data_atCE2B:
.incbin "rom-prg/objects/data-block-atCE2B.bin"

Data_atCE41:
.incbin "rom-prg/objects/data-block-atCE41.bin"

Data_atCE57:
.incbin "rom-prg/objects/data-block-atCE57.bin"

Data_atCEAC:
.incbin "rom-prg/objects/data-block-atCEAC.bin"

Data_atCF01:
.incbin "rom-prg/objects/data-block-atCF01.bin"

Data_atCF80:
.incbin "rom-prg/objects/data-block-atCF80.bin"

Data_atD00D:
.incbin "rom-prg/objects/data-block-atD00D.bin"

Data_atD09A:
.incbin "rom-prg/objects/data-block-atD09A.bin"

Data_atD127:
.incbin "rom-prg/objects/data-block-atD127.bin" ;;;;

Data_atD1B4:
.incbin "rom-prg/objects/data-block-atD1B4.bin"

Data_atD241:
.incbin "rom-prg/objects/data-block-atD241.bin"

Data_atD291:
.incbin "rom-prg/objects/data-block-atD291.bin"

Data_atD2E1:
.incbin "rom-prg/objects/data-block-atD2E1.bin"

Data_atD331:
.incbin "rom-prg/objects/data-block-atD331.bin"

Data_atD381:
.incbin "rom-prg/objects/data-block-atD381.bin"

Data_atD3C1:
.incbin "rom-prg/objects/data-block-atD3C1.bin"

Data_atD401:
.incbin "rom-prg/objects/data-block-atD401.bin"

Data_atD426:
.incbin "rom-prg/objects/data-block-atD426.bin"

Data_atD448:
.incbin "rom-prg/objects/data-block-atD448.bin" ;;; parei aqui
