
.word Data_atC945 ;$c945
.word Data_atC951 ;$c951
.word Data_atC95D ;$c95d
.word Data_atC969 ;$c969
.word Data_atC975 ;$c975
.word Data_atC981 ;$c981
.word Data_atC98D ;$c98d
.word Data_atC999 ;$c999 
.word Data_atC9A5 ;$c9a5
.word Data_atC9B1 ;$c9b1
.word Data_atC9BD ;$c9bd
.word Data_atC9C9 ;$c9c9 
.word Data_atC9D5 ;$c9d5
.word Data_atC9E1 ;$c9e1
.word Data_atC9ED ;$c9ed
.word Data_atC9F9 ;$c9f9 
.word Data_atCA05 ;$ca05
.word $ca11
.word $ca1d
.word $ca29
.word $ca35
.word $ca41
.word $ca4d
.word $ca59 
.word $ca65
.word $ca71
.word $ca7d
.word $ca89  
.word $ca95
.word $caa1
.word $caad
.word $cab9 
.word $cac5
.word $cad1
.word $cadd
.word $cae9 
.word $caf5
.word $cb01
.word $cb0d
.word $cb19 
.word $cb25
.word $cb31
.word $cb3d
.word $cb49 
.word $cb55
.word $cb61
.word $cb6d
.word $cb79 
.word $cb85
.word $cb91
.word $cb9d
.word $cba9 
.word $cbb5
.word $cbc1
.word $cbcd
.word $cbd9 
.word $cbe5
.word $cbf1
.word $cbfd
.word $cc09 
.word $cc15
.word $cc21
.word $cc2d
.word $cc39 
.word $cc45
.word $cc51
.word $cc5d
.word $cc69 
.word $cc75
.word $cc81

Data_atC945:
.word Data_atCC8D ;$cc8d 
.incbin "rom-prg/objects/data-block-atC947.bin"

Data_atC951:
.word Data_atCCF5 ;$ccf5 
.incbin "rom-prg/objects/data-block-atC953.bin"

Data_atC95D:
.word $cd5d
.incbin "rom-prg/objects/data-block-atC95F.bin"

Data_atC969:
.word $ce2b
.incbin "rom-prg/objects/data-block-atC96B.bin"

Data_atC975:
.word $ce41
.incbin "rom-prg/objects/data-block-atC977.bin"

Data_atC981:
.word $ce57
.incbin "rom-prg/objects/data-block-atC983.bin"

Data_atC98D:
.word $ceac
.incbin "rom-prg/objects/data-block-atC98F.bin"

Data_atC999:
.word $cf01
.incbin "rom-prg/objects/data-block-atC99B.bin"

Data_atC9A5:
.word $cf80
.incbin "rom-prg/objects/data-block-atC9A7.bin"

Data_atC9B1:
.word $d00d
.incbin "rom-prg/objects/data-block-atC9B3.bin"

Data_atC9BD:
.word $d09a
.incbin "rom-prg/objects/data-block-atC9BF.bin"

Data_atC9C9:
.word $d127
.incbin "rom-prg/objects/data-block-atC9CB.bin"

Data_atC9D5:
.word $d1b4
.incbin "rom-prg/objects/data-block-atC9D7.bin"

Data_atC9E1:
.word $d241
.incbin "rom-prg/objects/data-block-atC9E3.bin"

Data_atC9ED:
.word $d291
.incbin "rom-prg/objects/data-block-atC9EF.bin"

Data_atC9F9:
.word $d2E1
.incbin "rom-prg/objects/data-block-atC9FB.bin"

Data_atCA05:
.word $d331
.incbin "rom-prg/objects/data-block-atCA07.bin" ;;;; PAREI AQUI XXX

; ===; Each one of the above has one below (enemy AI?)

Data_atCC8D:
.incbin "rom-prg/objects/data-block-atCC8D.bin"

Data_atCCF5:
.incbin "rom-prg/objects/data-block-atCCF5.bin"
