; The offset used to read from this list, 
; stored in objectType_58, is the first byte in each file. 

; The address itself is stored in objectPtr_38

.word Data_atBB9D	;	index $00
.word Data_atBBA9	;	index $01
.word Data_atBBB5	;	index $02
.word Data_atBBC1	;	index $03
.word Data_atBBCD	;	index $04
.word Data_atBBD9	;	index $05
.word Data_atBBE5	;	index $06
.word Data_atBBF1	;	index $07
.word Data_atBBFD	;	index $08
.word Data_atBC09	;	index $09
.word Data_atBC15	;	index $0A
.word Data_atBC21	;	index $0B
.word Data_atBC2D	;	index $0C
.word Data_atBC39	;	index $0D
.word Data_atBC45	;	index $0E
.word Data_atBC51	;	index $0F

.word Data_atBC5D	;	index $10
.word Data_atBC69	;	index $11
.word Data_atBC75	;	index $12
.word Data_atBC81	;	index $13
.word Data_atBC8D	;	index $14
.word Data_atBC99	;	index $15
.word Data_atBCA5	;	index $16
.word Data_atBCB1	;	index $17
.word Data_atBCBD	;	index $18
.word Data_atBCC9	;	index $19
.word Data_atBCD5	;	index $1A
.word Data_atBCE1	;	index $1B
.word Data_atBCED	;	index $1C
.word Data_atBCF9	;	index $1D
.word Data_atBD05	;	index $1E
.word Data_atBD11	;	index $1F

Data_atBB9D:
.word Data_atBD1D ;$bd1d 
.incbin "objects/data/data2/data-block-atBB9F.bin"

Data_atBBA9:
.word Data_atBD31 ;$bd31 
.incbin "objects/data/data2/data-block-atBBAB.bin"

Data_atBBB5:
.word Data_atBD45 ;$bd45
.incbin "objects/data/data2/data-block-atBBB7.bin"

Data_atBBC1:
.word Data_atBD6D ;$bd6d
.incbin "objects/data/data2/data-block-atBBC3.bin"

Data_atBBCD:
.word Data_atBD95 ;$bd95
.incbin "objects/data/data2/data-block-atBBCF.bin"

Data_atBBD9:
.word Data_atBE17 ;$be17
.incbin "objects/data/data2/data-block-atBBDB.bin"

Data_atBBE5:
.word Data_atBE41 ;$be41
.incbin "objects/data/data2/data-block-atBBE7.bin"

Data_atBBF1:
.word Data_atBE6E ;$be6e
.incbin "objects/data/data2/data-block-atBBF3.bin"

Data_atBBFD:
.word Data_atBE9E ;$be9e
.incbin "objects/data/data2/data-block-atBBFF.bin"

Data_atBC09:
.word Data_atBEEC ;$beec
.incbin "objects/data/data2/data-block-atBC0B.bin"

Data_atBC15:
.word Data_atBF3A ;$bf3a
.incbin "objects/data/data2/data-block-atBC17.bin"

Data_atBC21:
.word Data_atBF88 ;$bf88
.incbin "objects/data/data2/data-block-atBC23.bin"

Data_atBC2D:
.word Data_atBFD4 ;$bfd4 
.incbin "objects/data/data2/data-block-atBC2F.bin"

Data_atBC39:
.word Data_atC020 ;$c020 
.incbin "objects/data/data2/data-block-atBC3B.bin"

Data_atBC45:
.word Data_atC07C ;$c07c 
.incbin "objects/data/data2/data-block-atBC47.bin"

Data_atBC51:
.word Data_atC0D8 ;$c0d8
.incbin "objects/data/data2/data-block-atBC53.bin"

Data_atBC5D:
.word Data_atC153 ;$c153
.incbin "objects/data/data2/data-block-atBC5F.bin"

Data_atBC69:
.word Data_atC1B5 ;$c1b5
.incbin "objects/data/data2/data-block-atBC6B.bin"

Data_atBC75:
.word Data_atC1CC ;$c1cc
.incbin "objects/data/data2/data-block-atBC77.bin"

Data_atBC81:
.word Data_atC22E ;$c22e 
.incbin "objects/data/data2/data-block-atBC83.bin"

Data_atBC8D:
.word Data_atC2A9 ;$c2a9
.incbin "objects/data/data2/data-block-atBC8F.bin"

Data_atBC99:
.word Data_atC2CB ;$c2cb
.incbin "objects/data/data2/data-block-atBC9B.bin"

Data_atBCA5:
.word Data_atC2DF ;$c2df
.incbin "objects/data/data2/data-block-atBCA7.bin"

Data_atBCB1:
.word Data_atC2FF ;$c2ff
.incbin "objects/data/data2/data-block-atBCB3.bin"

Data_atBCBD:
.word Data_atC325 ;$c325
.incbin "objects/data/data2/data-block-atBCBF.bin"

Data_atBCC9:
.word Data_atC339 ;$c339
.incbin "objects/data/data2/data-block-atBCCB.bin"

Data_atBCD5:
.word Data_atC34D ;$c34d
.incbin "objects/data/data2/data-block-atBCD7.bin"

Data_atBCE1:
.word Data_atC3CA ;$c3ca
.incbin "objects/data/data2/data-block-atBCE3.bin"

Data_atBCED:
.word Data_atC447 ;$c447
.incbin "objects/data/data2/data-block-atBCEF.bin"

Data_atBCF9:
.word Data_atC44F ;$c44f
.incbin "objects/data/data2/data-block-atBCFB.bin"

Data_atBD05:
.word Data_atC485 ;$c485
.incbin "objects/data/data2/data-block-atBD87.bin"

Data_atBD11:
.word Data_atC4BB ;$c4bb
.incbin "objects/data/data2/data-block-atBD13.bin"

; ===; Each one of the above has one below (enemy AI?)

Data_atBD1D:
.incbin "objects/data/data2/data-block-atBD1D.bin"

Data_atBD31:
.incbin "objects/data/data2/data-block-atBD31.bin"

Data_atBD45:
.incbin "objects/data/data2/data-block-atBD45.bin"

Data_atBD6D:
.incbin "objects/data/data2/data-block-atBD6D.bin"

Data_atBD95:
.incbin "objects/data/data2/data-block-atBD95.bin"

Data_atBE17:
.incbin "objects/data/data2/data-block-atBE17.bin"

Data_atBE41:
.incbin "objects/data/data2/data-block-atBE41.bin"

Data_atBE6E:
.incbin "objects/data/data2/data-block-atBE6E.bin"

Data_atBE9E:
.incbin "objects/data/data2/data-block-atBE9E.bin"

Data_atBEEC:
.incbin "objects/data/data2/data-block-atBEEC.bin"

Data_atBF3A:
.incbin "objects/data/data2/data-block-atBF3A.bin"

Data_atBF88:
.incbin "objects/data/data2/data-block-atBF88.bin"

Data_atBFD4:
.incbin "objects/data/data2/data-block-atBFD4.bin" ; <<<< BANK0(16K) would end within this file's range.

Data_atC020:
.incbin "objects/data/data2/data-block-atC020.bin"

Data_atC07C:
.incbin "objects/data/data2/data-block-atC07C.bin"

Data_atC0D8:
.incbin "objects/data/data2/data-block-atC0D8.bin"

Data_atC153:
.incbin "objects/data/data2/data-block-atC153.bin"

Data_atC1B5:
.incbin "objects/data/data2/data-block-atC1B5.bin"

Data_atC1CC:
.incbin "objects/data/data2/data-block-atC1CC.bin"

Data_atC22E:
.incbin "objects/data/data2/data-block-atC22E.bin"

Data_atC2A9:
.incbin "objects/data/data2/data-block-atC2A9.bin"

Data_atC2CB:
.incbin "objects/data/data2/data-block-atC2CB.bin"

Data_atC2DF:
.incbin "objects/data/data2/data-block-atC2DF.bin"

Data_atC2FF:
.incbin "objects/data/data2/data-block-atC2FF.bin"

Data_atC325:
.incbin "objects/data/data2/data-block-atC325.bin"

Data_atC339:
.incbin "objects/data/data2/data-block-atC339.bin"

Data_atC34D:
.incbin "objects/data/data2/data-block-atC34D.bin"

Data_atC3CA:
.incbin "objects/data/data2/data-block-atC3CA.bin"

Data_atC447:
.incbin "objects/data/data2/data-block-atC447.bin"

Data_atC44F:
.incbin "objects/data/data2/data-block-atC44F.bin"

Data_atC485:
.incbin "objects/data/data2/data-block-atC485.bin"

Data_atC4BB:
.incbin "objects/data/data2/data-block-atC4BB.bin"