; The offset used to read from this list,
; stored in objectType_58, is the first byte in each file.

; The address itself is stored in objectPtr_38

.word Data_atBB9D	;	index $00
.word Data_atBBA9	;	index $01
.word Data_atBBB5	;	index $02
.word Data_atBBC1	;	index $03
.word Data_atBBCD	;	index $04
.word Data_atBBD9	;	index $05
.word Data_atBBE5	;	index $06
.word Data_atBBF1	;	index $07
.word Data_atBBFD	;	index $08
.word Data_atBC09	;	index $09
.word Data_atBC15	;	index $0A
.word Data_atBC21	;	index $0B
.word Data_atBC2D	;	index $0C
.word Data_atBC39	;	index $0D
.word Data_atBC45	;	index $0E
.word Data_atBC51	;	index $0F

.word Data_atBC5D	;	index $10
.word Data_atBC69	;	index $11
.word Data_atBC75	;	index $12
.word Data_atBC81	;	index $13
.word Data_atBC8D	;	index $14
.word Data_atBC99	;	index $15
.word Data_atBCA5	;	index $16
.word Data_atBCB1	;	index $17
.word Data_atBCBD	;	index $18
.word Data_atBCC9	;	index $19
.word Data_atBCD5	;	index $1A
.word Data_atBCE1	;	index $1B
.word Data_atBCED	;	index $1C
.word Data_atBCF9	;	index $1D
.word Data_atBD05	;	index $1E
.word Data_atBD11	;	index $1F

Data_atBB9D:
.word Data_atBD1D ;$bd1d
.include "objects/profiles/enemy_profile_20.inc"
;.incbin "objects/data/data2/data-block-atBB9F.bin"

Data_atBBA9:
.word Data_atBD31 ;$bd31
.include "objects/profiles/enemy_profile_20.inc"
;.incbin "objects/data/data2/data-block-atBBAB.bin"

Data_atBBB5:
.word Data_atBD45 ;$bd45
.include "objects/profiles/enemy_profile_21.inc"
;.incbin "objects/data/data2/data-block-atBBB7.bin"

Data_atBBC1:
.word Data_atBD6D ;$bd6d
.include "objects/profiles/enemy_profile_21.inc"
;.incbin "objects/data/data2/data-block-atBBC3.bin"

Data_atBBCD:
.word Data_atBD95 ;$bd95
.include "objects/profiles/enemy_profile_22.inc"
;.incbin "objects/data/data2/data-block-atBBCF.bin"

Data_atBBD9:
.word Data_atBE17 ;$be17
.include "objects/profiles/enemy_profile_23.inc"
;.incbin "objects/data/data2/data-block-atBBDB.bin"

Data_atBBE5:
.word Data_atBE41 ;$be41
.include "objects/profiles/enemy_profile_24.inc"
;.incbin "objects/data/data2/data-block-atBBE7.bin"

Data_atBBF1:
.word Data_atBE6E ;$be6e
.include "objects/profiles/enemy_profile_25.inc"
;.incbin "objects/data/data2/data-block-atBBF3.bin"

Data_atBBFD:
.word Data_atBE9E ;$be9e
.include "objects/profiles/enemy_profile_26.inc"
;.incbin "objects/data/data2/data-block-atBBFF.bin"

Data_atBC09:
.word Data_atBEEC ;$beec
.include "objects/profiles/enemy_profile_0D.inc"
;.incbin "objects/data/data2/data-block-atBC0B.bin"

Data_atBC15:
.word Data_atBF3A ;$bf3a
.include "objects/profiles/enemy_profile_0D.inc"
;.incbin "objects/data/data2/data-block-atBC17.bin"

Data_atBC21:
.word Data_atBF88 ;$bf88
.include "objects/profiles/enemy_profile_27.inc"
;.incbin "objects/data/data2/data-block-atBC23.bin"

Data_atBC2D:
.word Data_atBFD4 ;$bfd4
.include "objects/profiles/enemy_profile_28.inc"
;.incbin "objects/data/data2/data-block-atBC2F.bin"

Data_atBC39:
.word Data_atC020 ;$c020
.include "objects/profiles/enemy_profile_29.inc"
;.incbin "objects/data/data2/data-block-atBC3B.bin"

Data_atBC45:
.word Data_atC07C ;$c07c
.include "objects/profiles/enemy_profile_0C.inc"
;.incbin "objects/data/data2/data-block-atBC47.bin"

Data_atBC51:
.word Data_atC0D8 ;$c0d8
.include "objects/profiles/enemy_profile_2A.inc"
;.incbin "objects/data/data2/data-block-atBC53.bin"

Data_atBC5D:
.word Data_atC153 ;$c153
.include "objects/profiles/enemy_profile_00.inc"
;.incbin "objects/data/data2/data-block-atBC5F.bin"

Data_atBC69:
.word Data_atC1B5 ;$c1b5
.include "objects/profiles/enemy_profile_2B.inc"
;.incbin "objects/data/data2/data-block-atBC6B.bin"

Data_atBC75:
.word Data_atC1CC ;$c1cc
.include "objects/profiles/enemy_profile_00.inc"
;.incbin "objects/data/data2/data-block-atBC77.bin"

Data_atBC81:
.word Data_atC22E ;$c22e
.include "objects/profiles/enemy_profile_2A.inc"
;.incbin "objects/data/data2/data-block-atBC83.bin"

Data_atBC8D:
.word Data_atC2A9 ;$c2a9
.include "objects/profiles/enemy_profile_2C.inc"
;.incbin "objects/data/data2/data-block-atBC8F.bin"

Data_atBC99:
.word Data_atC2CB ;$c2cb
.include "objects/profiles/enemy_profile_2D.inc"
;.incbin "objects/data/data2/data-block-atBC9B.bin"

Data_atBCA5:
.word Data_atC2DF ;$c2df
.include "objects/profiles/enemy_profile_2E.inc"
;.incbin "objects/data/data2/data-block-atBCA7.bin"

Data_atBCB1:
.word Data_atC2FF ;$c2ff
.include "objects/profiles/enemy_profile_2F.inc"
;.incbin "objects/data/data2/data-block-atBCB3.bin"

Data_atBCBD:
.word Data_atC325 ;$c325
.include "objects/profiles/enemy_profile_30.inc"
;.incbin "objects/data/data2/data-block-atBCBF.bin"

Data_atBCC9:
.word Data_atC339 ;$c339
.include "objects/profiles/enemy_profile_30.inc"
;.incbin "objects/data/data2/data-block-atBCCB.bin"

Data_atBCD5:
.word Data_atC34D ;$c34d
.include "objects/profiles/enemy_profile_31.inc"
;.incbin "objects/data/data2/data-block-atBCD7.bin"

Data_atBCE1:
.word Data_atC3CA ;$c3ca
.include "objects/profiles/enemy_profile_32.inc"
;.incbin "objects/data/data2/data-block-atBCE3.bin"

Data_atBCED:
.word Data_atC447 ;$c447
.include "objects/profiles/enemy_profile_33.inc"
;.incbin "objects/data/data2/data-block-atBCEF.bin"

Data_atBCF9:
.word Data_atC44F ;$c44f
.include "objects/profiles/enemy_profile_34.inc"
;.incbin "objects/data/data2/data-block-atBCFB.bin"

Data_atBD05:
.word Data_atC485 ;$c485
.include "objects/profiles/enemy_profile_35.inc"
;.incbin "objects/data/data2/data-block-atBD87.bin"

Data_atBD11:
.word Data_atC4BB ;$c4bb
.include "objects/profiles/enemy_profile_36.inc"
;.incbin "objects/data/data2/data-block-atBD13.bin"

; ===; Each one of the above has one below (enemy AI?)

Data_atBD1D:
;.incbin "objects/data/data2/data-block-atBD1D.bin"
.byte afBEDOUIN+0, -4, 0, acTIMER+1
.byte afBEDOUIN+1, -3, 0, acTIMER+1
.byte acLOOPN+5, 0
.byte afBEDOUIN+0, -3, 1
.byte afBEDOUIN+1, -2, 2
.byte acLOOPN+5, 10
.byte acLOOPBACK, 0

Data_atBD31:
;.incbin "objects/data/data2/data-block-atBD31.bin"
.byte afBEDOUIN+0, -4, 0, acTIMER+1
.byte afBEDOUIN+1, -3, 0, acTIMER+1
.byte acLOOPN+5, 0
.byte afBEDOUIN+0, -3, -1
.byte afBEDOUIN+1, -2, -2
.byte acLOOPN+5, 10
.byte acLOOPBACK, 0

Data_atBD45:
;.incbin "objects/data/data2/data-block-atBD45.bin"
.byte afBEDOUIN+0, -4, 0, acTIMER+1
.byte afBEDOUIN+1, -3, 0, acTIMER+1
.byte acLOOPN+5, 0
.byte afBEDOUIN+0, -3, 1
.byte afBEDOUIN+1, -2, 2
.byte acLOOPN+5, 10
.byte afBEDOUIN+1, 0, 0
.byte afBEDOUIN+1, -1, 0
.byte afBEDOUIN+0, 0, 0, acTIMER+4
.byte acLOOPN+5, $12
.byte afBEDOUIN+0, -5, 1
.byte afBEDOUIN+1, -3, 1
.byte acLOOPN+10, $1E
.byte acLOOPBACK, 0

Data_atBD6D:
;.incbin "objects/data/data2/data-block-atBD6D.bin"
.byte afBEDOUIN+0, -4, 0, acTIMER+1
.byte afBEDOUIN+1, -3, 0, acTIMER+1
.byte acLOOPN+5, 0
.byte afBEDOUIN+0, -3, -1
.byte afBEDOUIN+1, -2, -2
.byte acLOOPN+5, 10
.byte afBEDOUIN+1, 0, 0
.byte afBEDOUIN+1, -1, 0
.byte afBEDOUIN+0, 0, 0, acTIMER+4
.byte acLOOPN+5, $12
.byte afBEDOUIN+0, -5, -1
.byte afBEDOUIN+1, -3, -1
.byte acLOOPN+10, $1E
.byte acLOOPBACK, 0

Data_atBD95:
;.incbin "objects/data/data2/data-block-atBD95.bin"
.byte afBEDOUIN+0, -2, 2, acTIMER+1
.byte afBEDOUIN+1, -2, 2, acTIMER+1
.byte afBEDOUIN+0, -2, 2, acTIMER+1
.byte afBEDOUIN+1, -2, 2, acTIMER+1
.byte afBEDOUIN+0, -2, 2, acTIMER+1
.byte afBEDOUIN+1, -2, 1, acTIMER+1
.byte afBEDOUIN+0, -3, 1, acTIMER+1
.byte afBEDOUIN+1, -3, 1, acTIMER+1
.byte afBEDOUIN+0, -3, 0, acTIMER+1
.byte afBEDOUIN+1, -3, -1, acTIMER+1
.byte afBEDOUIN+0, -3, -1, acTIMER+1
.byte afBEDOUIN+1, -2, -1, acTIMER+1
.byte afBEDOUIN+0, -2, -2, acTIMER+1
.byte afBEDOUIN+1, -2, -2, acTIMER+1
.byte afBEDOUIN+0, -2, -2, acTIMER+1
.byte afBEDOUIN+1, -2, -2, acTIMER+1
.byte afBEDOUIN+0, -2, -2, acTIMER+1
.byte afBEDOUIN+1, -2, -2, acTIMER+1
.byte afBEDOUIN+0, -2, -2, acTIMER+1
.byte afBEDOUIN+1, -2, -2, acTIMER+1
.byte afBEDOUIN+0, -2, -2, acTIMER+1
.byte afBEDOUIN+1, -2, -2, acTIMER+1
.byte afBEDOUIN+0, -2, -1, acTIMER+1
.byte afBEDOUIN+1, -3, -1, acTIMER+1
.byte afBEDOUIN+0, -3, -1, acTIMER+1
.byte afBEDOUIN+1, -3, 0, acTIMER+1
.byte afBEDOUIN+0, -3, 1, acTIMER+1
.byte afBEDOUIN+1, -3, 1, acTIMER+1
.byte afBEDOUIN+0, -2, 1, acTIMER+1
.byte afBEDOUIN+1, -2, 2, acTIMER+1
.byte afBEDOUIN+0, -2, 2, acTIMER+1
.byte afBEDOUIN+1, -2, 2, acTIMER+1
.byte acLOOPBACK, 0

Data_atBE17:
;.incbin "objects/data/data2/data-block-atBE17.bin"
.byte afJINN+1, 2, 2, acTIMER+4
.byte afJINN+0, 2, 2, acTIMER+4
.byte afJINN+1, 3, 1, acTIMER+4
.byte afJINN+0, 4, 1, acTIMER+4
.byte afJINN+1, -1, 2, acTIMER+4
.byte afJINN+0, -1, 2, acTIMER+4
.byte afJINN+1, -2, 1, acTIMER+4
.byte afJINN+0, -3, 1, acTIMER+4
.byte acLOOPN+3, 0
.byte afJINN+0, -3, 3, acTIMER+1
.byte acLOOPN+10, $22
.byte acLOOPBACK, 0

Data_atBE41:
;.incbin "objects/data/data2/data-block-atBE41.bin"
.byte afJINN+0, -3, 1
.byte afJINN+0, -1, 0, acTIMER+1
.byte acLOOPN+8, 0
.byte afJINN+1, 2, 2, acTIMER+2
.byte afJINN+0, 2, 2, acTIMER+2
.byte afJINN+1, 3, 1, acTIMER+2
.byte afJINN+0, 4, 1, acTIMER+2
.byte afJINN+1, -3, 2, acTIMER+2
.byte afJINN+0, -3, 2, acTIMER+2
.byte afJINN+1, -4, 1, acTIMER+2
.byte afJINN+0, -5, 1, acTIMER+2
.byte acLOOPN+3, 9
.byte acLOOPBACK, 0

Data_atBE6E:
;.incbin "objects/data/data2/data-block-atBE6E.bin"
.byte afJINN+1, -2, -1
.byte afJINN+1, -2, -1, acTIMER+1
.byte afJINN+1, -2, -1
.byte afJINN+1, -2, -1, acTIMER+1
.byte acLOOPN+10, 0
.byte afJINN+0, 0, 3
.byte afJINN+1, 0, 3
.byte afJINN+0, 0, 3
.byte afJINN+1, 0, 3
.byte acLOOPN+8, $10
.byte afJINN+1, -2, -2, acTIMER+1
.byte afJINN+1, -2, -2
.byte afJINN+1, -2, -2, acTIMER+1
.byte afJINN+1, -2, -2
.byte acLOOPN+17, $1E
.byte acLOOPBACK, $10

Data_atBE9E:
;.incbin "objects/data/data2/data-block-atBE9E.bin"
.byte afBEE+1, -1, 1
.byte afBEE+1, -1, 1
.byte afBEE+1, -1, 1
.byte afBEE+0, -1, 1
.byte afBEE+0, -1, 1
.byte afBEE+0, -1, 1
.byte afBEE+1, -1, -1
.byte afBEE+1, -1, -1
.byte afBEE+1, -1, -1
.byte afBEE+0, -1, -1
.byte afBEE+0, -1, -1
.byte afBEE+0, -1, -1
.byte acLOOPN+5, 0
.byte afBEE+1, -2, 2
.byte afBEE+1, -2, 2
.byte afBEE+1, -2, 2
.byte afBEE+0, -2, 2
.byte afBEE+0, -2, 2
.byte afBEE+0, -2, 2
.byte afBEE+1, -2, -2
.byte afBEE+1, -2, -2
.byte afBEE+1, -2, -2
.byte afBEE+0, -2, -2
.byte afBEE+0, -2, -2
.byte afBEE+0, -2, -2
.byte acLOOPN+5, $26
.byte acLOOPBACK, 0

Data_atBEEC:
;.incbin "objects/data/data2/data-block-atBEEC.bin"
.byte afBEE+1, -1, 1
.byte afBEE+1, -1, 1
.byte afBEE+1, -1, 1
.byte afBEE+0, -1, 1
.byte afBEE+0, -1, 1
.byte afBEE+0, -1, 1
.byte afBEE+1, -1, -2
.byte afBEE+1, -1, -2
.byte afBEE+1, -1, -2
.byte afBEE+0, -1, -2
.byte afBEE+0, -1, -2
.byte afBEE+0, -1, -2
.byte acLOOPN+3, 0
.byte afBEE+1, -2, 2
.byte afBEE+1, -2, 2
.byte afBEE+1, -2, 2
.byte afBEE+0, -2, 2
.byte afBEE+0, -2, 2
.byte afBEE+0, -2, 2
.byte afBEE+1, -2, -2
.byte afBEE+1, -2, -2
.byte afBEE+1, -2, -2
.byte afBEE+0, -2, -2
.byte afBEE+0, -2, -2
.byte afBEE+0, -2, -2
.byte acLOOPN+3, $26
.byte acLOOPBACK, 0

Data_atBF3A:
;.incbin "objects/data/data2/data-block-atBF3A.bin"
.byte afBEE+1, -1, 2
.byte afBEE+1, -1, 2
.byte afBEE+1, -1, 2
.byte afBEE+0, -1, 2
.byte afBEE+0, -1, 2
.byte afBEE+0, -1, 2
.byte afBEE+1, -1, -1
.byte afBEE+1, -1, -1
.byte afBEE+1, -1, -1
.byte afBEE+0, -1, -1
.byte afBEE+0, -1, -1
.byte afBEE+0, -1, -1
.byte acLOOPN+3, 0
.byte afBEE+1, -2, 2
.byte afBEE+1, -2, 2
.byte afBEE+1, -2, 2
.byte afBEE+0, -2, 2
.byte afBEE+0, -2, 2
.byte afBEE+0, -2, 2
.byte afBEE+1, -2, -2
.byte afBEE+1, -2, -2
.byte afBEE+1, -2, -2
.byte afBEE+0, -2, -2
.byte afBEE+0, -2, -2
.byte afBEE+0, -2, -2
.byte acLOOPN+3, $26
.byte acLOOPBACK, 0

Data_atBF88:
;.incbin "objects/data/data2/data-block-atBF88.bin"
.byte afBEE+1, -1, 1
.byte afBEE+1, -1, 1
.byte afBEE+1, -1, 1
.byte afBEE+0, -1, 1
.byte afBEE+0, -1, 1
.byte afBEE+0, -1, 1
.byte afBEE+1, -1, -1
.byte afBEE+1, -1, -1
.byte afBEE+1, -1, -1
.byte afBEE+0, -1, -1
.byte afBEE+0, -1, -1
.byte afBEE+0, -1, -1
.byte acLOOPN+3, 0
.byte afBEE+1, -2, -6
.byte afBEE+1, -2, -6
.byte afBEE+1, -2, -5
.byte afBEE+0, -2, -5
.byte afBEE+0, -2, -4
.byte afBEE+0, -2, -4
.byte afBEE+1, -2, -3
.byte afBEE+1, -2, -3
.byte afBEE+1, -2, -2
.byte afBEE+0, -2, -2
.byte afBEE+0, -2, -1
.byte afBEE+0, -2, -1
.byte acLOOPBACK, 0

Data_atBFD4:
;.incbin "objects/data/data2/data-block-atBFD4.bin" ; <<<< BANK0(16K) would end within this file's range.
.byte afBEE+1, -1, 1
.byte afBEE+1, -1, 1
.byte afBEE+1, -1, 1
.byte afBEE+0, -1, 1
.byte afBEE+0, -1, 1
.byte afBEE+0, -1, 1
.byte afBEE+1, -1, -1
.byte afBEE+1, -1, -1
.byte afBEE+1, -1, -1
.byte afBEE+0, -1, -1
.byte afBEE+0, -1, -1
.byte afBEE+0, -1, -1
.byte acLOOPN+3, 0
.byte afBEE+1, -2, 6
.byte afBEE+1, -2, 6
.byte afBEE+1, -2, 5
.byte afBEE+0, -2, 5
.byte afBEE+0, -2, 4
.byte afBEE+0, -2, 4
.byte afBEE+1, -2, 3
.byte afBEE+1, -2, 3
.byte afBEE+1, -2, 2
.byte afBEE+0, -2, 2
.byte afBEE+0, -2, 1
.byte afBEE+0, -2, 1
.byte acLOOPBACK, 0

Data_atC020:
;.incbin "objects/data/data2/data-block-atC020.bin"
.byte afBEE+1, -1, 1
.byte afBEE+1, -1, 1
.byte afBEE+1, -1, 1
.byte afBEE+0, -1, 1
.byte afBEE+0, -1, 1
.byte afBEE+0, -1, 1
.byte afBEE+1, -1, -1
.byte afBEE+1, -1, -1
.byte afBEE+1, -1, -1
.byte afBEE+0, -1, -1
.byte afBEE+0, -1, -1
.byte afBEE+0, -1, -1
.byte acLOOPN+3, 0
.byte afBEE+1, 0, 0
.byte afBEE+1, 0, 1
.byte afBEE+1, 0, 0
.byte afBEE+0, 0, 1
.byte afBEE+0, 0, 0
.byte afBEE+0, 0, 1
.byte acLOOPN+6, $26
.byte afBEE+1, -2, -1
.byte afBEE+0, -2, -1
.byte afBEE+1, -3, -1
.byte afBEE+0, -3, -2
.byte afBEE+1, -4, -2
.byte afBEE+0, -4, -2
.byte afBEE+1, -4, -3
.byte afBEE+0, -5, -3
.byte afBEE+1, -5, -4
.byte afBEE+0, -5, -4
.byte acLOOPN+2, $3A
.byte acLOOPBACK, 0

Data_atC07C:
;.incbin "objects/data/data2/data-block-atC07C.bin"
.byte afBEE+1, -1, 1
.byte afBEE+1, -1, 1
.byte afBEE+1, -1, 1
.byte afBEE+0, -1, 1
.byte afBEE+0, -1, 1
.byte afBEE+0, -1, 1
.byte afBEE+1, -1, -1
.byte afBEE+1, -1, -1
.byte afBEE+1, -1, -1
.byte afBEE+0, -1, -1
.byte afBEE+0, -1, -1
.byte afBEE+0, -1, -1
.byte acLOOPN+3, 0
.byte afBEE+1, 0, 0
.byte afBEE+1, 0, -1
.byte afBEE+1, 0, 0
.byte afBEE+0, 0, -1
.byte afBEE+0, 0, 0
.byte afBEE+0, 0, -1
.byte acLOOPN+6, $26
.byte afBEE+1, -2, 1
.byte afBEE+0, -2, 1
.byte afBEE+1, -3, 1
.byte afBEE+0, -3, 2
.byte afBEE+1, -4, 2
.byte afBEE+0, -4, 2
.byte afBEE+1, -4, 3
.byte afBEE+0, -5, 3
.byte afBEE+1, -5, 4
.byte afBEE+0, -5, 4
.byte acLOOPN+2, $3A
.byte acLOOPBACK, 0

Data_atC0D8:
;.incbin "objects/data/data2/data-block-atC0D8.bin"
.byte afBEE+0, -2, 0, acTIMER+1
.byte afBEE+0, -2, 1
.byte afBEE+0, -2, 0, acTIMER+1
.byte afBEE+1, -2, 0
.byte afBEE+1, -2, -1, acTIMER+1
.byte afBEE+1, -2, 0
.byte acLOOPN+7, 0
.byte afBEE+0, -1, -2, acTIMER+1
.byte afBEE+0, -1, -2, acTIMER+1
.byte afBEE+0, -2, -3
.byte afBEE+1, -2, -3, acTIMER+1
.byte afBEE+1, -2, -4, acTIMER+1
.byte afBEE+1, -2, -4
.byte afBEE+1, -2, -5, acTIMER+1
.byte afBEE+0, -2, -5, acTIMER+1
.byte afBEE+0, -2, -6
.byte afBEE+0, -2, -6, acTIMER+1
.byte afBEE+0, -3, -4, acTIMER+1
.byte afBEE+1, -3, -4
.byte afBEE+1, -3, -3, acTIMER+1
.byte afBEE+1, -3, -3, acTIMER+1
.byte afBEE+0, -3, -2
.byte afBEE+0, -3, -1, acTIMER+1
.byte afBEE+0, -3, 0, acTIMER+1
.byte afBEE+1, -3, 0
.byte afBEE+1, -3, 0, acTIMER+1
.byte afBEE+0, -3, 1, acTIMER+1
.byte afBEE+0, -3, 2
.byte afBEE+1, -3, 3, acTIMER+1
.byte afBEE+1, -3, 4
.byte afBEE+0, -3, 3, acTIMER+1
.byte afBEE+0, -3, 2
.byte afBEE+1, -3, 1, acTIMER+1
.byte afBEE+0, -3, 1
.byte acLOOPBACK, $72

Data_atC153:
;.incbin "objects/data/data2/data-block-atC153.bin"
.byte afBEE+0, -2, 0, acTIMER+1
.byte afBEE+0, -2, 1
.byte afBEE+0, -2, 0, acTIMER+1
.byte afBEE+1, -2, 0
.byte afBEE+1, -2, -1, acTIMER+1
.byte afBEE+1, -2, 0
.byte acLOOPN+7, 0
.byte afBEE+0, -1, -2, acTIMER+1
.byte afBEE+0, -2, -3, acTIMER+1
.byte afBEE+1, -2, -4
.byte afBEE+1, -2, -5, acTIMER+1
.byte afBEE+0, -2, -6, acTIMER+1
.byte afBEE+0, -3, -4
.byte afBEE+1, -3, -3, acTIMER+1
.byte afBEE+1, -3, -2, acTIMER+1
.byte afBEE+0, -3, -1
.byte afBEE+0, -3, 0, acTIMER+1
.byte afBEE+1, -3, 0, acTIMER+1
.byte afBEE+1, -3, 0
.byte afBEE+0, -3, 1, acTIMER+1
.byte afBEE+0, -3, 2, acTIMER+1
.byte afBEE+1, -3, 3
.byte afBEE+1, -3, 4, acTIMER+1
.byte afBEE+0, -3, 3, acTIMER+1
.byte afBEE+0, -3, 2
.byte afBEE+1, -3, 2, acTIMER+1
.byte afBEE+0, -3, 2
.byte acLOOPBACK, $59

Data_atC1B5:
;.incbin "objects/data/data2/data-block-atC1B5.bin"
.byte afBEE+0, -2, 0, acTIMER+1
.byte afBEE+0, -2, 1
.byte afBEE+0, -2, 0, acTIMER+1
.byte afBEE+1, -2, 0
.byte afBEE+1, -2, -1, acTIMER+1
.byte afBEE+1, -2, 0
.byte acLOOPBACK, 0

Data_atC1CC:
;.incbin "objects/data/data2/data-block-atC1CC.bin"
.byte afBEE+0, -2, 0, acTIMER+1
.byte afBEE+0, -2, 1
.byte afBEE+0, -2, 0, acTIMER+1
.byte afBEE+1, -2, 0
.byte afBEE+1, -2, -1, acTIMER+1
.byte afBEE+1, -2, 0
.byte acLOOPN+7, 0
.byte afBEE+0, -1, 2, acTIMER+1
.byte afBEE+0, -2, 3, acTIMER+1
.byte afBEE+1, -2, 4
.byte afBEE+1, -2, 5, acTIMER+1
.byte afBEE+0, -2, 6, acTIMER+1
.byte afBEE+0, -3, 4
.byte afBEE+1, -3, 3, acTIMER+1
.byte afBEE+1, -3, 2, acTIMER+1
.byte afBEE+0, -3, 1
.byte afBEE+0, -3, 0, acTIMER+1
.byte afBEE+1, -3, 0, acTIMER+1
.byte afBEE+1, -3, 0
.byte afBEE+0, -3, -1, acTIMER+1
.byte afBEE+0, -3, -2, acTIMER+1
.byte afBEE+1, -3, -3
.byte afBEE+1, -3, -4, acTIMER+1
.byte afBEE+0, -3, -3, acTIMER+1
.byte afBEE+0, -3, -2
.byte afBEE+1, -3, -2, acTIMER+1
.byte afBEE+0, -3, -2
.byte acLOOPBACK, $59

Data_atC22E:
;.incbin "objects/data/data2/data-block-atC22E.bin"
.byte afBEE+0, -2, 0, acTIMER+1
.byte afBEE+0, -2, 1
.byte afBEE+0, -2, 0, acTIMER+1
.byte afBEE+1, -2, 0
.byte afBEE+1, -2, -1, acTIMER+1
.byte afBEE+1, -2, 0
.byte acLOOPN+7, 0
.byte afBEE+0, -1, 2, acTIMER+1
.byte afBEE+0, -1, 2, acTIMER+1
.byte afBEE+0, -2, 3
.byte afBEE+1, -2, 3, acTIMER+1
.byte afBEE+1, -2, 4, acTIMER+1
.byte afBEE+1, -2, 4
.byte afBEE+1, -2, 5, acTIMER+1
.byte afBEE+0, -2, 5, acTIMER+1
.byte afBEE+0, -2, 6
.byte afBEE+0, -2, 6, acTIMER+1
.byte afBEE+0, -3, 4, acTIMER+1
.byte afBEE+1, -3, 4
.byte afBEE+1, -3, 3, acTIMER+1
.byte afBEE+1, -3, 3, acTIMER+1
.byte afBEE+0, -3, 2
.byte afBEE+0, -3, 1, acTIMER+1
.byte afBEE+0, -3, 0, acTIMER+1
.byte afBEE+1, -3, 0
.byte afBEE+1, -3, 0, acTIMER+1
.byte afBEE+0, -3, -1, acTIMER+1
.byte afBEE+0, -3, -2
.byte afBEE+1, -3, -3, acTIMER+1
.byte afBEE+1, -3, -4
.byte afBEE+0, -3, -3, acTIMER+1
.byte afBEE+0, -3, -2
.byte afBEE+1, -3, -1, acTIMER+1
.byte afBEE+0, -3, -1
.byte acLOOPBACK, $72

Data_atC2A9:
;.incbin "objects/data/data2/data-block-atC2A9.bin"
.byte afBAT+0, -2, -1, acTIMER+1
.byte afBAT+1, -2, -1, acTIMER+1
.byte afBAT+2, -2, -1, acTIMER+1
.byte afBAT+1, -2, -1, acTIMER+1
.byte afBAT+0, -2, -1, acTIMER+1
.byte afBAT+1, -2, -1, acTIMER+1
.byte afBAT+2, -2, -1, acTIMER+1
.byte afBAT+1, -2, -1, acTIMER+1
.byte acLOOPBACK, 0

Data_atC2CB:
;.incbin "objects/data/data2/data-block-atC2CB.bin"
.byte afBAT+0, -2, 1
.byte afBAT+0, -2, 1
.byte afBAT+1, -2, 1
.byte afBAT+1, -2, 1
.byte afBAT+2, -2, 1
.byte afBAT+2, -2, 1
.byte acLOOPBACK, 0

Data_atC2DF:
;.incbin "objects/data/data2/data-block-atC2DF.bin"
.byte afBAT+0, -3, -4
.byte afBAT+1, -4, -2, acTIMER+1
.byte afBAT+2, -4, -1
.byte afBAT+0, -2, 4
.byte afBAT+1, -3, 3, acTIMER+1
.byte afBAT+2, -2, -3
.byte afBAT+0, 1, 2
.byte afBAT+1, -4, -1, acTIMER+1
.byte afBAT+2, 0, 0
.byte acLOOPBACK, 0

Data_atC2FF:
;.incbin "objects/data/data2/data-block-atC2FF.bin"
.byte afBEE+1, -1, 1
.byte afBEE+1, -1, 1
.byte afBEE+1, -1, 1
.byte afBEE+0, -1, 1
.byte afBEE+0, -1, 1
.byte afBEE+0, -1, 1
.byte afBEE+1, -1, -1
.byte afBEE+1, -1, -1
.byte afBEE+1, -1, -1
.byte afBEE+0, -1, -1
.byte afBEE+0, -1, -1
.byte afBEE+0, -1, -1
.byte acLOOPBACK, 0

Data_atC325:
;.incbin "objects/data/data2/data-block-atC325.bin"
.byte afBEE+1, -1, 1
.byte afBEE+1, -1, 0
.byte afBEE+1, -1, 1
.byte afBEE+0, -1, 1
.byte afBEE+0, -1, 0
.byte afBEE+0, -1, 1
.byte acLOOPBACK, 0

Data_atC339:
;.incbin "objects/data/data2/data-block-atC339.bin"
.byte afBEE+0, -1, -1
.byte afBEE+0, -1, 0
.byte afBEE+0, -1, -1
.byte afBEE+1, -1, -1
.byte afBEE+1, -1, 0
.byte afBEE+1, -1, -1
.byte acLOOPBACK, 0

Data_atC34D:
;.incbin "objects/data/data2/data-block-atC34D.bin"
.byte afBAT+0, -2, 0, acTIMER+1
.byte afBAT+0, -2, 1
.byte afBAT+1, -2, 0, acTIMER+1
.byte afBAT+1, -2, 0
.byte afBAT+2, -2, -1, acTIMER+1
.byte afBAT+2, -2, 0
.byte acLOOPN+7, 0
.byte afBAT+0, -1, -2, acTIMER+1
.byte afBAT+0, -1, -2, acTIMER+1
.byte afBAT+1, -2, -3
.byte afBAT+1, -2, -3, acTIMER+1
.byte afBAT+2, -2, -4, acTIMER+1
.byte afBAT+2, -2, -4
.byte afBAT+0, -2, -5, acTIMER+1
.byte afBAT+0, -2, -5, acTIMER+1
.byte afBAT+1, -2, -6
.byte afBAT+1, -2, -6, acTIMER+1
.byte afBAT+2, -3, -4, acTIMER+1
.byte afBAT+2, -3, -4
.byte afBAT+0, -3, -3, acTIMER+1
.byte afBAT+0, -3, -3, acTIMER+1
.byte afBAT+1, -3, -2
.byte afBAT+1, -3, -1, acTIMER+1
.byte afBAT+2, -3, 0, acTIMER+1
.byte afBAT+2, -3, 0
.byte afBAT+0, -3, 0, acTIMER+1
.byte afBAT+0, -3, 1, acTIMER+1
.byte afBAT+1, -3, 2
.byte afBAT+1, -3, 3, acTIMER+1
.byte afBAT+2, -3, 4
.byte afBAT+2, -3, 3, acTIMER+1
.byte afBAT+0, -3, 2, acTIMER+2
.byte afBAT+1, -3, 1, acTIMER+1
.byte afBAT+2, -3, 1, acTIMER+2
.byte acLOOPBACK, $6F

Data_atC3CA:
;.incbin "objects/data/data2/data-block-atC3CA.bin"
.byte afBAT+0, -2, 0, acTIMER+1
.byte afBAT+0, -2, 1
.byte afBAT+1, -2, 0, acTIMER+1
.byte afBAT+1, -2, 0
.byte afBAT+2, -2, -1, acTIMER+1
.byte afBAT+2, -2, 0
.byte acLOOPN+7, 0
.byte afBAT+0, -1, 2, acTIMER+1
.byte afBAT+0, -1, 2, acTIMER+1
.byte afBAT+1, -2, 3
.byte afBAT+1, -2, 3, acTIMER+1
.byte afBAT+2, -2, 4, acTIMER+1
.byte afBAT+2, -2, 4
.byte afBAT+0, -2, 5, acTIMER+1
.byte afBAT+0, -2, 5, acTIMER+1
.byte afBAT+1, -2, 6
.byte afBAT+1, -2, 6, acTIMER+1
.byte afBAT+2, -3, 4, acTIMER+1
.byte afBAT+2, -3, 4
.byte afBAT+0, -3, 3, acTIMER+1
.byte afBAT+0, -3, 3, acTIMER+1
.byte afBAT+1, -3, 2
.byte afBAT+1, -3, 1, acTIMER+1
.byte afBAT+2, -3, 0, acTIMER+1
.byte afBAT+2, -3, 0
.byte afBAT+0, -3, 0, acTIMER+1
.byte afBAT+0, -3, -1, acTIMER+1
.byte afBAT+1, -3, -2
.byte afBAT+1, -3, -3, acTIMER+1
.byte afBAT+2, -3, -4
.byte afBAT+2, -3, -3, acTIMER+1
.byte afBAT+0, -3, -2, acTIMER+2
.byte afBAT+1, -3, -1, acTIMER+1
.byte afBAT+2, -3, -1, acTIMER+1
.byte acLOOPBACK, $6F

Data_atC447:
;.incbin "objects/data/data2/data-block-atC447.bin"
.byte afBEDOUIN+0, -3, 0
.byte afBEDOUIN+1, -3, 0
.byte acLOOPBACK, 0

Data_atC44F:
;.incbin "objects/data/data2/data-block-atC44F.bin"
.byte afJINN+0, 0, 0, acTIMER+1
.byte acLOOPN+9, 0
.byte afJINN+1, -2, -1
.byte afJINN+1, -2, -1, acTIMER+1
.byte afJINN+1, -2, -1
.byte afJINN+1, -2, -1, acTIMER+1
.byte acLOOPN+10, 6
.byte afJINN+0, 0, 3
.byte afJINN+1, 0, 3
.byte afJINN+0, 0, 3
.byte afJINN+1, 0, 3
.byte acLOOPN+8, $16
.byte afJINN+1, -2, -2, acTIMER+1
.byte afJINN+1, -2, -2
.byte afJINN+1, -2, -2, acTIMER+1
.byte afJINN+1, -2, -2
.byte acLOOPN+17, $24
.byte acLOOPBACK, $16

Data_atC485:
;.incbin "objects/data/data2/data-block-atC485.bin"
.byte afJINN+0, 0, 0, acTIMER+1
.byte acLOOPN+19, 0
.byte afJINN+1, -2, -1
.byte afJINN+1, -2, -1, acTIMER+1
.byte afJINN+1, -2, -1
.byte afJINN+1, -2, -1, acTIMER+1
.byte acLOOPN+10, 6
.byte afJINN+0, 0, 3
.byte afJINN+1, 0, 3
.byte afJINN+0, 0, 3
.byte afJINN+1, 0, 3
.byte acLOOPN+8, $16
.byte afJINN+1, -2, -2, acTIMER+1
.byte afJINN+1, -2, -2
.byte afJINN+1, -2, -2, acTIMER+1
.byte afJINN+1, -2, -2
.byte acLOOPN+17, $24
.byte acLOOPBACK, $16

Data_atC4BB:
;.incbin "objects/data/data2/data-block-atC4BB.bin"
.byte afCROC+1, -6, 0, acTIMER+2
.byte acLOOPN+10, 0
.byte afCROC+0, -5, -1, acTIMER+2
.byte acLOOPN+10, 6
.byte afCROC+0, 5, 1, acTIMER+2
.byte acLOOPN+10, $0C
.byte afCROC+0, 0, -3, acTIMER+2
.byte acLOOPN+20, $12
.byte afCROC+0, -6, -1, acTIMER+2
.byte acLOOPN+12, $18
.byte afCROC+0, 6, -1, acTIMER+2
.byte acLOOPN+12, $1E
.byte afCROC+0, 0, -3, acTIMER+2
.byte acLOOPN+20, $24
.byte afCROC+0, -5, 1, acTIMER+2
.byte acLOOPN+10, $2A
.byte afCROC+0, 5, -1, acTIMER+2
.byte acLOOPN+10, $30
.byte afCROC+0, 2, 3, acTIMER+2
.byte afCROC+0, 3, 4, acTIMER+3
.byte afCROC+1, -3, 5, acTIMER+2
.byte afCROC+1, -2, 3, acTIMER+3
.byte acLOOPN+8, $36
.byte afCROC+0, 0, 8, acTIMER+2
.byte afCROC+0, 0, 9, acTIMER+2
.byte acLOOPBACK, 6