.word DATA_S3_01, DATA_S3_02, DATA_S3_03, DATA_S3_04
.word DATA_S3_05, DATA_S3_06, DATA_S3_07, DATA_S3_08
.word DATA_S3_09, DATA_S3_10, DATA_S3_11, DATA_S3_04
.word DATA_S3_12, DATA_S3_13, DATA_S3_14

.word $ffff

DATA_S3_01: ; $c52d
.incbin "data/objects/data-block-atC52D.bin"

DATA_S3_02: ; $c565
.incbin "data/objects/data-block-atC565.bin"

DATA_S3_03: ; $c58e
.incbin "data/objects/data-block-atC58E.bin"

DATA_S3_04: ; $c5b7
.incbin "data/objects/data-block-atC5B7.bin"

DATA_S3_05: ; $c5fc
.incbin "data/objects/data-block-atC5FC.bin"

DATA_S3_06: ; $c653
.incbin "data/objects/data-block-atC653.bin"

DATA_S3_07: ; $c6b1
.incbin "data/objects/data-block-atC6B1.bin"

DATA_S3_08: ; $c6df
.incbin "data/objects/data-block-atC6DF.bin"

DATA_S3_09: ; $c710
.incbin "data/objects/data-block-atC710.bin"

DATA_S3_10: ; $c750
.incbin "data/objects/data-block-atC750.bin"

DATA_S3_11: ; $c7a1
.incbin "data/objects/data-block-atC7A1.bin"

DATA_S3_12: ; $c802
.incbin "data/objects/data-block-atC802.bin"

DATA_S3_13: ; $c84c
.incbin "data/objects/data-block-atC84C.bin"

DATA_S3_14: ; $c8b2
.incbin "data/objects/data-block-atC8B2.bin"

