.word WAVE_S3_01, WAVE_S3_02, WAVE_S3_03, WAVE_S3_04
.word WAVE_S3_05, WAVE_S3_06, WAVE_S3_07, WAVE_S3_08
.word WAVE_S3_09, WAVE_S3_10, WAVE_S3_11, WAVE_S3_04
.word WAVE_S3_12, WAVE_S3_13, WAVE_S3_14

.word $ffff

WAVE_S3_01: ; $c52d
.incbin "objects/data/stage3/data-block-atC52D.bin"

WAVE_S3_02: ; $c565
.incbin "objects/data/stage3/data-block-atC565.bin"

WAVE_S3_03: ; $c58e
.incbin "objects/data/stage3/data-block-atC58E.bin"

WAVE_S3_04: ; $c5b7
.incbin "objects/data/stage3/data-block-atC5B7.bin"

WAVE_S3_05: ; $c5fc
.incbin "objects/data/stage3/data-block-atC5FC.bin"

WAVE_S3_06: ; $c653
.incbin "objects/data/stage3/data-block-atC653.bin"

WAVE_S3_07: ; $c6b1
.incbin "objects/data/stage3/data-block-atC6B1.bin"

WAVE_S3_08: ; $c6df
.incbin "objects/data/stage3/data-block-atC6DF.bin"

WAVE_S3_09: ; $c710
.incbin "objects/data/stage3/data-block-atC710.bin"

WAVE_S3_10: ; $c750
.incbin "objects/data/stage3/data-block-atC750.bin"

WAVE_S3_11: ; $c7a1
.incbin "objects/data/stage3/data-block-atC7A1.bin"

WAVE_S3_12: ; $c802
.incbin "objects/data/stage3/data-block-atC802.bin"

WAVE_S3_13: ; $c84c
.incbin "objects/data/stage3/data-block-atC84C.bin"

WAVE_S3_14: ; $c8b2
.incbin "objects/data/stage3/data-block-atC8B2.bin"

