; This file contains all 14 enemy waves in Stage 4

; Address book
.addr WAVE_S4_01, WAVE_S4_02, WAVE_S4_03, WAVE_S4_04
.addr WAVE_S4_05, WAVE_S4_06, WAVE_S4_07, WAVE_S4_08
.addr WAVE_S4_09, WAVE_S4_10, WAVE_S4_11, WAVE_S4_12
.addr WAVE_S4_13, WAVE_S4_01, WAVE_S4_14

.addr $ffff

WAVE_S4_01: ; $e3c6
.incbin "objects/data/stage4/data-block-atE3C6.bin"

WAVE_S4_02: ; $e413
.incbin "objects/data/stage4/data-block-atE413.bin"

WAVE_S4_03: ; $e46a
.incbin "objects/data/stage4/data-block-atE46A.bin"

WAVE_S4_04: ; $e4ac
.incbin "objects/data/stage4/data-block-atE4AC.bin"

WAVE_S4_05: ; $e4e7
.incbin "objects/data/stage4/data-block-atE4E7.bin"

WAVE_S4_06: ; $e552
.incbin "objects/data/stage4/data-block-atE552.bin"

WAVE_S4_07: ; $e5a1
.incbin "objects/data/stage4/data-block-atE5A1.bin"

WAVE_S4_08: ; $e5eb
.incbin "objects/data/stage4/data-block-atE5EB.bin"

WAVE_S4_09: ; $e63a
.incbin "objects/data/stage4/data-block-atE63A.bin"

WAVE_S4_10: ; $e670
.incbin "objects/data/stage4/data-block-atE670.bin"

WAVE_S4_11: ; $e6c4
.incbin "objects/data/stage4/data-block-atE6C4.bin"

WAVE_S4_12: ; $e731
.incbin "objects/data/stage4/data-block-atE731.bin"

WAVE_S4_13: ; $e7ba
.incbin "objects/data/stage4/data-block-atE7BA.bin"

WAVE_S4_14: ; $e7fa
.incbin "objects/data/stage4/data-block-atE7FA.bin"
;.res 7



