; The offset used to read from this list, 
; stored in objectType_58, is the first byte in each file. 

; The address itself is stored in objectPtr_38

.addr Data_atC945	;	index $00
.addr Data_atC951	;	index $01
.addr Data_atC95D	;	index $02
.addr Data_atC969	;	index $03
.addr Data_atC975	;	index $04
.addr Data_atC981	;	index $05
.addr Data_atC98D	;	index $06
.addr Data_atC999	;	index $07
.addr Data_atC9A5	;	index $08
.addr Data_atC9B1	;	index $09
.addr Data_atC9BD	;	index $0A
.addr Data_atC9C9	;	index $0B
.addr Data_atC9D5	;	index $0C
.addr Data_atC9E1	;	index $0D
.addr Data_atC9ED	;	index $0E
.addr Data_atC9F9	;	index $0F

.addr Data_atCA05	;	index $10
.addr Data_atCA11	;	index $11
.addr Data_atCA1D	;	index $12
.addr Data_atCA29	;	index $13
.addr Data_atCA35	;	index $14
.addr Data_atCA41	;	index $15
.addr Data_atCA4D	;	index $16
.addr Data_atCA59	;	index $17
.addr Data_atCA65	;	index $18
.addr Data_atCA71	;	index $19
.addr Data_atCA7D	;	index $1A
.addr Data_atCA89	;	index $1B
.addr Data_atCA95	;	index $1C
.addr Data_atCAA1	;	index $1D
.addr Data_atCAAD	;	index $1E
.addr Data_atCAB9	;	index $1F

.addr Data_atCAC5	;	index $20
.addr Data_atCAD1	;	index $21
.addr Data_atCADD	;	index $22
.addr Data_atCAE9	;	index $23
.addr Data_atCAF5	;	index $24
.addr Data_atCB01	;	index $25
.addr Data_atCB0D	;	index $26
.addr Data_atCB19	;	index $27
.addr Data_atCB25	;	index $28
.addr Data_atCB31	;	index $29
.addr Data_atCB3D	;	index $2A
.addr Data_atCB49	;	index $2B
.addr Data_atCB55	;	index $2C
.addr Data_atCB61	;	index $2D
.addr Data_atCB6D	;	index $2E
.addr Data_atCB79	;	index $2F

.addr Data_atCB85	;	index $30
.addr Data_atCB91	;	index $31
.addr Data_atCB9D	;	index $32
.addr Data_atCBA9	;	index $33
.addr Data_atCBB5	;	index $34
.addr Data_atCBC1	;	index $35
.addr Data_atCBCD	;	index $36
.addr Data_atCBD9	;	index $37
.addr Data_atCBE5	;	index $38
.addr Data_atCBF1	;	index $39
.addr Data_atCBFD	;	index $3A
.addr Data_atCC09	;	index $3B
.addr Data_atCC15	;	index $3C
.addr Data_atCC21	;	index $3D
.addr Data_atCC2D	;	index $3E
.addr Data_atCC39	;	index $3F

.addr Data_atCC45	;	index $40
.addr Data_atCC51	;	index $41
.addr Data_atCC5D	;	index $42
.addr Data_atCC69	;	index $43
.addr Data_atCC75	;	index $44
.addr Data_atCC81	;	index $45

Data_atC945:
.addr Data_atCC8D ;$cc8d 
.incbin "objects/data/data3/data-block-atC947.bin"

Data_atC951:
.addr Data_atCCF5 ;$ccf5 
.incbin "objects/data/data3/data-block-atC953.bin"

Data_atC95D:
.addr Data_atCD5D ;$cd5d
.incbin "objects/data/data3/data-block-atC95F.bin"

Data_atC969:
.addr Data_atCE2B ;$ce2b
.incbin "objects/data/data3/data-block-atC96B.bin"

Data_atC975:
.addr Data_atCE41 ;$ce41
.incbin "objects/data/data3/data-block-atC977.bin"

Data_atC981:
.addr Data_atCE57 ;$ce57
.incbin "objects/data/data3/data-block-atC983.bin"

Data_atC98D:
.addr Data_atCEAC ;$ceac
.incbin "objects/data/data3/data-block-atC98F.bin"

Data_atC999:
.addr Data_atCF01 ;$cf01
.incbin "objects/data/data3/data-block-atC99B.bin"

Data_atC9A5:
.addr Data_atCF80 ;$cf80
.incbin "objects/data/data3/data-block-atC9A7.bin"

Data_atC9B1:
.addr Data_atD00D ;$d00d
.incbin "objects/data/data3/data-block-atC9B3.bin"

Data_atC9BD:
.addr Data_atD09A ;$d09a
.incbin "objects/data/data3/data-block-atC9BF.bin"

Data_atC9C9:
.addr Data_atD127 ;$d127
.incbin "objects/data/data3/data-block-atC9CB.bin"

Data_atC9D5:
.addr Data_atD1B4 ;$d1b4
.incbin "objects/data/data3/data-block-atC9D7.bin"

Data_atC9E1:
.addr Data_atD241 ;$d241
.incbin "objects/data/data3/data-block-atC9E3.bin"

Data_atC9ED:
.addr Data_atD291 ;$d291
.incbin "objects/data/data3/data-block-atC9EF.bin"

Data_atC9F9:
.addr Data_atD2E1 ;$d2E1
.incbin "objects/data/data3/data-block-atC9FB.bin"

Data_atCA05:
.addr Data_atD331 ;$d331
.incbin "objects/data/data3/data-block-atCA07.bin" 

Data_atCA11:
.addr Data_atD381 ;$d381
.incbin "objects/data/data3/data-block-atCA13.bin" 

Data_atCA1D:
.addr Data_atD3C1 ;$d3c1
.incbin "objects/data/data3/data-block-atCA1F.bin";$ca1d

Data_atCA29:
.addr Data_atD401 ;$d401
.incbin "objects/data/data3/data-block-atCA31.bin";$ca29

Data_atCA35:
.addr Data_atD426 ;$d426
.incbin "objects/data/data3/data-block-atCA37.bin";$ca35

Data_atCA41:
.addr Data_atD448 ;$d448
.incbin "objects/data/data3/data-block-atCA43.bin";$ca41

Data_atCA4D:
.addr Data_atD502
.incbin "objects/data/data3/data-block-atCA4F.bin";$ca4d

Data_atCA59:
.addr Data_atD52E
.incbin "objects/data/data3/data-block-atCA5B.bin";$ca59 

Data_atCA65:
.addr Data_atD5AA
.incbin "objects/data/data3/data-block-atCA67.bin";$ca65

Data_atCA71:
.addr Data_atD630
.incbin "objects/data/data3/data-block-atCA73.bin";$ca71

Data_atCA7D:
.addr Data_atD6B6
.incbin "objects/data/data3/data-block-atCA7F.bin";$ca7d

Data_atCA89:
.addr Data_atD73C
.incbin "objects/data/data3/data-block-atCA8B.bin";$ca89  

Data_atCA95:
.addr Data_atD7C2
.incbin "objects/data/data3/data-block-atCA97.bin";$ca95

Data_atCAA1:
.addr Data_atD848
.incbin "objects/data/data3/data-block-atCAA3.bin";$caa1

Data_atCAAD:
.addr Data_atD860
.incbin "objects/data/data3/data-block-atCAAF.bin";$caad

Data_atCAB9:
.addr Data_atD878
.incbin "objects/data/data3/data-block-atCABB.bin";$cab9 

Data_atCAC5:
.addr Data_atD88D
.incbin "objects/data/data3/data-block-atCAC7.bin";$cac5

Data_atCAD1:
.addr Data_atD8A2
.incbin "objects/data/data3/data-block-atCAD3.bin";$cad1

Data_atCADD:
.addr Data_atD8B1
.incbin "objects/data/data3/data-block-atCADF.bin";$cadd

Data_atCAE9:
.addr Data_atD8C0
.incbin "objects/data/data3/data-block-atCAEB.bin";$cae9 

Data_atCAF5:
.addr Data_atD905
.incbin "objects/data/data3/data-block-atCAF7.bin";$caf5

Data_atCB01:
.addr Data_atD97C
.incbin "objects/data/data3/data-block-atCB03.bin";$cb01

Data_atCB0D:
.addr Data_atD9F9
.incbin "objects/data/data3/data-block-atCB0F.bin";$cb0d

Data_atCB19:
.addr Data_atDA76
.incbin "objects/data/data3/data-block-atCB1B.bin";$cb19 

Data_atCB25:
.addr Data_atDAF3
.incbin "objects/data/data3/data-block-atCB27.bin";$cb25

Data_atCB31:
.addr Data_atDB6A
.incbin "objects/data/data3/data-block-atCB33.bin";$cb31

Data_atCB3D:
.addr Data_atDBE7
.incbin "objects/data/data3/data-block-atCB3F.bin";$cb3d

Data_atCB49:
.addr Data_atDC64
.incbin "objects/data/data3/data-block-atCB4B.bin";$cb49 

Data_atCB55:
.addr Data_atDCE1
.incbin "objects/data/data3/data-block-atCB57.bin";$cb55

Data_atCB61:
.addr Data_atDD9B
.incbin "objects/data/data3/data-block-atCB63.bin";$cb61

Data_atCB6D:
.addr Data_atDDA0
.incbin "objects/data/data3/data-block-atCB6F.bin";$cb6d

Data_atCB79:
.addr Data_atDDA5
.incbin "objects/data/data3/data-block-atCB7B.bin";$cb79 

Data_atCB85:
.addr Data_atDDAA
.incbin "objects/data/data3/data-block-atCB87.bin";$cb85

Data_atCB91:
.addr Data_atDE0F
.incbin "objects/data/data3/data-block-atCB93.bin";$cb91

Data_atCB9D:
.addr Data_atDE78
.incbin "objects/data/data3/data-block-atCB9F.bin";$cb9d

Data_atCBA9:
.addr Data_atDEDD
.incbin "objects/data/data3/data-block-atCBAB.bin";$cba9 

Data_atCBB5:
.addr Data_atDF45
.incbin "objects/data/data3/data-block-atCBB7.bin";$cbb5

Data_atCBC1:
.addr Data_atDFAA
.incbin "objects/data/data3/data-block-atCBC3.bin";$cbc1

Data_atCBCD:
.addr Data_atE013
.incbin "objects/data/data3/data-block-atCBCF.bin";$cbcd

Data_atCBD9:
.addr Data_atE078
.incbin "objects/data/data3/data-block-atCBDB.bin";$cbd9 

Data_atCBE5:
.addr Data_atE0E1
.incbin "objects/data/data3/data-block-atCBE7.bin";$cbe5

Data_atCBF1:
.addr Data_atE0F3
.incbin "objects/data/data3/data-block-atCBF3.bin";$cbf1

Data_atCBFD:
.addr Data_atE109
.incbin "objects/data/data3/data-block-atCBFF.bin";$cbfd

Data_atCC09:
.addr Data_atE142
.incbin "objects/data/data3/data-block-atCC0B.bin";$cc09 

Data_atCC15:
.addr Data_atE161
.incbin "objects/data/data3/data-block-atCC17.bin";$cc15

Data_atCC21:
.addr Data_atE180
.incbin "objects/data/data3/data-block-atCC23.bin";$cc21

Data_atCC2D:
.addr Data_atE19F
.incbin "objects/data/data3/data-block-atCC2F.bin";$cc2d

Data_atCC39:
.addr Data_atE1BE
.incbin "objects/data/data3/data-block-atCC3B.bin";$cc39 

Data_atCC45:
.addr Data_atE1DD
.incbin "objects/data/data3/data-block-atCC47.bin";$cc45

Data_atCC51:
.addr Data_atE1FC
.incbin "objects/data/data3/data-block-atCC53.bin";$cc51

Data_atCC5D:
.addr Data_atE21B
.incbin "objects/data/data3/data-block-atCC5F.bin";$cc5d

Data_atCC69:
.addr Data_atE262
.incbin "objects/data/data3/data-block-atCC6B.bin";$cc69 

Data_atCC75:
.addr Data_atE2B5
.incbin "objects/data/data3/data-block-atCC77.bin";$cc75

Data_atCC81:
.addr Data_atE801 ; <<< THIS ONE POINTS WAY AHEAD, Stage 04????
.incbin "objects/data/data3/data-block-atCC83.bin";$cc81

; ===; Each one of the above has one below (enemy AI?)

Data_atCC8D:
.incbin "objects/data/data3/data-block-atCC8D.bin"

Data_atCCF5: 
.incbin "objects/data/data3/data-block-atCCF5.bin"

Data_atCD5D:
.incbin "objects/data/data3/data-block-atCD5D.bin"

Data_atCE2B:
.incbin "objects/data/data3/data-block-atCE2B.bin"

Data_atCE41:
.incbin "objects/data/data3/data-block-atCE41.bin"

Data_atCE57:
.incbin "objects/data/data3/data-block-atCE57.bin"

Data_atCEAC:
.incbin "objects/data/data3/data-block-atCEAC.bin"

Data_atCF01:
.incbin "objects/data/data3/data-block-atCF01.bin"

Data_atCF80:
.incbin "objects/data/data3/data-block-atCF80.bin"

Data_atD00D:
.incbin "objects/data/data3/data-block-atD00D.bin"

Data_atD09A:
.incbin "objects/data/data3/data-block-atD09A.bin"

Data_atD127:
.incbin "objects/data/data3/data-block-atD127.bin"

Data_atD1B4:
.incbin "objects/data/data3/data-block-atD1B4.bin"

Data_atD241:
.incbin "objects/data/data3/data-block-atD241.bin"

Data_atD291:
.incbin "objects/data/data3/data-block-atD291.bin"

Data_atD2E1:
.incbin "objects/data/data3/data-block-atD2E1.bin"

Data_atD331:
.incbin "objects/data/data3/data-block-atD331.bin"

Data_atD381:
.incbin "objects/data/data3/data-block-atD381.bin"

Data_atD3C1:
.incbin "objects/data/data3/data-block-atD3C1.bin"

Data_atD401:
.incbin "objects/data/data3/data-block-atD401.bin"

Data_atD426:
.incbin "objects/data/data3/data-block-atD426.bin"

Data_atD448:
.incbin "objects/data/data3/data-block-atD448.bin"
;.res 186 ; ba

Data_atD502:
.incbin "objects/data/data3/data-block-atD502.bin"
;.res 44 ; 2c

Data_atD52E:
.incbin "objects/data/data3/data-block-atD52E.bin"
;.res 124 ; 7c

Data_atD5AA:
; Next 5 files are almost the same, 
; except for byte $08, here $C3.
.incbin "objects/data/data3/data-block-atD5AA.bin"
;.res 134 ; 86

Data_atD630:
; Almost the same as the previous one, 
; except for byte $08, here $C6.
.incbin "objects/data/data3/data-block-atD630.bin"
;.res 134 ; 86

Data_atD6B6:
; Almost the same as the previous one, 
; except for byte $08, here $C9
.incbin "objects/data/data3/data-block-atD6B6.bin"
;.res 134 ; 86

Data_atD73C:
; Almost the same as the previous one, 
; except for byte $08, here $CC
.incbin "objects/data/data3/data-block-atD73C.bin"
;.res 134 ; 86

Data_atD7C2:
; Almost the same as the previous one, 
; except for byte $08, here $CF.
.incbin "objects/data/data3/data-block-atD7C2.bin"
;.res 134 ; 86

Data_atD848:
.incbin "objects/data/data3/data-block-atD848.bin"
;.res 24 ; 18

Data_atD860:
.incbin "objects/data/data3/data-block-atD860.bin"
;.res 24 ; 18

Data_atD878:
.incbin "objects/data/data3/data-block-atD878.bin"
;.res 21 ; 15

Data_atD88D:
.incbin "objects/data/data3/data-block-atD88D.bin"
;.res 21 ; 15

Data_atD8A2:
.incbin "objects/data/data3/data-block-atD8A2.bin"
;.res 15 ; f

Data_atD8B1:
.incbin "objects/data/data3/data-block-atD8B1.bin"
;.res 15 ; f

Data_atD8C0:
.incbin "objects/data/data3/data-block-atD8C0.bin"
;.res 69 ; 45

Data_atD905:
.incbin "objects/data/data3/data-block-atD905.bin"
;.res 119 ; 77

Data_atD97C:
; Next 3 files are almost the same, 
; except for byte $04, here $C4.
.incbin "objects/data/data3/data-block-atD97C.bin"
;.res 125 ; 7d

Data_atD9F9:
; Almost the same as the previous one, 
; except for byte $04, here $C9.
.incbin "objects/data/data3/data-block-atD9F9.bin"
;.res 125 ; 7d

Data_atDA76:
; Almost the same as the previous one, 
; except for byte $04, here $CE.
.incbin "objects/data/data3/data-block-atDA76.bin"
;.res 125 ; 7d

Data_atDAF3:
.incbin "objects/data/data3/data-block-atDAF3.bin"
;.res 119 ; 77

Data_atDB6A:
.incbin "objects/data/data3/data-block-atDB6A.bin"
;.res 125 ; 7d

Data_atDBE7:
.incbin "objects/data/data3/data-block-atDBE7.bin"
;.res 125 ; 7d

Data_atDC64:
.incbin "objects/data/data3/data-block-atDC64.bin"
;.res 125 ; 7d

Data_atDCE1:
.incbin "objects/data/data3/data-block-atDCE1.bin"
;.res 186 ; ba

Data_atDD9B:
.incbin "objects/data/data3/data-block-atDD9B.bin"
;.res 5 ; 5

Data_atDDA0:
.incbin "objects/data/data3/data-block-atDDA0.bin"
;.res 5 ; 5

Data_atDDA5:
.incbin "objects/data/data3/data-block-atDDA5.bin"
;.res 5 ; 5

Data_atDDAA:
.incbin "objects/data/data3/data-block-atDDAA.bin"
;.res 101 ; 65

Data_atDE0F:
.incbin "objects/data/data3/data-block-atDE0F.bin"
;.res 105 ; 69

Data_atDE78:
.incbin "objects/data/data3/data-block-atDE78.bin"
;.res 101 ; 65

Data_atDEDD:
.incbin "objects/data/data3/data-block-atDEDD.bin"
;.res 104 ; 68

Data_atDF45:
.incbin "objects/data/data3/data-block-atDF45.bin"
;.res 101 ; 65

Data_atDFAA:
.incbin "objects/data/data3/data-block-atDFAA.bin"
;.res 105 ; 69

Data_atE013:
.incbin "objects/data/data3/data-block-atE013.bin"
;.res 101 ; 65

Data_atE078:
.incbin "objects/data/data3/data-block-atE078.bin"
;.res 105 ; 69

Data_atE0E1:
.incbin "objects/data/data3/data-block-atE0E1.bin"
;.res 18 ; 12  

Data_atE0F3:
.incbin "objects/data/data3/data-block-atE0F3.bin"
;.res 22 ; 16

Data_atE109:
.incbin "objects/data/data3/data-block-atE109.bin"
;.res 57 ; 39

Data_atE142:
.incbin "objects/data/data3/data-block-atE142.bin"
;.res 31 ; 1F

Data_atE161:
.incbin "objects/data/data3/data-block-atE161.bin"
;.res 31 ; 1F

Data_atE180:
.incbin "objects/data/data3/data-block-atE180.bin"
;.res 31 ; 1F

Data_atE19F:
.incbin "objects/data/data3/data-block-atE19F.bin"
;.res 31 ; 1F

Data_atE1BE:
.incbin "objects/data/data3/data-block-atE1BE.bin"
;.res 31 ; 1F

Data_atE1DD:
.incbin "objects/data/data3/data-block-atE1DD.bin"
;.res 31 ; 1F

Data_atE1FC:
.incbin "objects/data/data3/data-block-atE1FC.bin"
;.res 31 ; 1F

Data_atE21B:
.incbin "objects/data/data3/data-block-atE21B.bin"
;.res 71 ; 47

Data_atE262:
.incbin "objects/data/data3/data-block-atE262.bin"
;.res 83 ; 53

Data_atE2B5:
.incbin "objects/data/data3/data-block-atE2B5.bin"
;.res 241