;.incbin "rom-prg/objects/temp-address-atE3A6.bin"
.addr DATA_S4_01, DATA_S4_02, DATA_S4_03, DATA_S4_04
.addr DATA_S4_05, DATA_S4_06, DATA_S4_07, DATA_S4_08
.addr DATA_S4_09, DATA_S4_10, DATA_S4_11, DATA_S4_12
.addr DATA_S4_13, DATA_S4_01, DATA_S4_14

.addr $ffff

DATA_S4_01: ; $e3c6
.incbin "rom-prg/objects/data-block-atE3C6.bin"

DATA_S4_02: ; $e413
.incbin "rom-prg/objects/data-block-atE413.bin"

DATA_S4_03: ; $e46a
.incbin "rom-prg/objects/data-block-atE46A.bin"

DATA_S4_04: ; $e4ac
.incbin "rom-prg/objects/data-block-atE4AC.bin"

DATA_S4_05: ; $e4e7
.incbin "rom-prg/objects/data-block-atE4E7.bin"

DATA_S4_06: ; $e552
.incbin "rom-prg/objects/data-block-atE552.bin"

DATA_S4_07: ; $e5a1
.incbin "rom-prg/objects/data-block-atE5A1.bin"

DATA_S4_08: ; $e5eb
.incbin "rom-prg/objects/data-block-atE5EB.bin"

DATA_S4_09: ; $e63a
.incbin "rom-prg/objects/data-block-atE63A.bin"

DATA_S4_10: ; $e670
.incbin "rom-prg/objects/data-block-atE670.bin"

DATA_S4_11: ; $e6c4
.incbin "rom-prg/objects/data-block-atE6C4.bin"

DATA_S4_12: ; $e731
.incbin "rom-prg/objects/data-block-atE731.bin"

DATA_S4_13: ; $e7ba
.incbin "rom-prg/objects/data-block-atE7BA.bin"

DATA_S4_14: ; $e7fa
.incbin "rom-prg/objects/data-block-atE7FA.bin"
;.res 7

Data_atE801:
;.res 70
.incbin "rom-prg/objects/data-block-atE801.bin"

