.addr Data_at9392
.addr Data_at9397
.addr Data_at939C
.addr Data_at93A1
.addr Data_at93A6
.addr Data_at93AB
.addr Data_at93B0
.addr Data_at93B5
.addr Data_at93BA
.addr Data_at93BF
.addr Data_at93C4

Data_at9392:
.byte $00, $00, $00, $FE, $00

Data_at9397:
.byte $01, $00, $00, $FE, $00 

Data_at939C:
.byte $02, $00, $00, $FE, $00

Data_at93A1:
.byte $03, $00, $00, $FE, $00

Data_at93A6:
.byte $04, $00, $00, $FE, $00

Data_at93AB:
.byte $05, $00, $00, $FE, $00

Data_at93B0:
.byte $06, $00, $00, $FE, $00

Data_at93B5:
.byte $07, $00, $00, $FE, $00

Data_at93BA:
.byte $08, $00, $00, $FE, $00

Data_at93BF:
.byte $09, $00, $00, $FE, $00

Data_at93C4:
.byte $14, $00, $00, $FE, $00
